language: minimal

services:
  - docker

env:
  - RAILS_ENV=test
  - RECAPTCHA_SECRET_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
  - RECAPTCHA_SITE_KEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI

before_script:
  - cp config/database.yml.travis config/database.yml
  - docker-compose build
  - docker-compose run web rake db:create db:schema:load

script:
  - docker-compose run web bundle exec rspec spec/
