language: ruby

services:
  - docker

before_script:
  - cp config/database.yml.travis config/database.yml
  - docker-compose build
  - docker-compose run web rake db:create db:migrate
  - export RECAPTCHA_SECRET_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
  - export RECAPTCHA_SITE_KEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI

script:
  - docker-compose run web bundle exec rspec spec/
