version: '3'
services:
  db:
    image: postgres:9.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  elastic:
    image: elasticsearch:2.4.5
    volumes:
      - ./tmp/elastic:/usr/share/elasticsearch/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - SEARCHBOX_URL=elastic
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elastic
